### ISSUE TITLE
Create "Terra Classic Integration Guidelines" presentation

### ISSUE THREAD

**Issue by ZaradarDFDS** [terra-rebels/classic-core#6]
What: Create simple to understand guidelines for dapp developers
Why: Enable 3rd parties to self-service their Terra Classic integration needs

Tasks:
[X] Create "TR .ppt template"
[X] Create "Terra Classic Integration Guidelines"

Acceptance Criteria:
[X] Integration guidelines are reviewed with devs
[X] Integration guidelines are published on GH

**Comment by sbjohansen** [comment]
Could be nice to add some examples of useful dapp's.

**Comment by Jfromdabay** [comment]
Looks good - quite straightforward, clear and complete from my point of view.
I really love how you first define every bound again making sure everybody is on the same stage and then create the reference to the terra classic part corresponding and then slightly begin to dive deeper .

**Comment by Jfromdabay** [comment]
Find attached the reviewed document with comments:
[terra_classic_integration_guidelines_reviewed_Jfromdabay.pptx](https://github.com/terra-rebels/classic-core/files/9189360/terra_classic_integration_guidelines_reviewed_Jfromdabay.pptx)

**Comment by ZaradarDFDS** [comment]
I have added the ppt to a new repo so we can version it: https://github.com/terra-rebels/architecture/blob/main/terra_classic_integration_guidelines.pptx

**Comment by ZaradarDFDS** [comment]
I reviewed the diff input and decided to just leave v0.1 AS-IS for now. @sbjohansen it would be great if you can add an appendix list of dapps at the end, this would be very useful. :) You should have the access needed to update the artifact.
